name: Rust

on:
  push:
    branches: [master]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest

        toolchain:
        - 1.62.1
        - stable
        - nightly

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        profile: minimal
        override: true
        components: rustfmt, clippy
    - uses: Swatinem/rust-cache@v1
      with:
        key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}-${{ matrix.toolchain }}
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
    - name: clippy
      run: cargo clippy -- --deny "warnings"
    - name: fmt
      run: cargo fmt -- --check

  linux-binary:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.62.1
        target: x86_64-unknown-linux-musl
        profile: minimal
        override: true
    - uses: Swatinem/rust-cache@v1
      with:
        key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}-1.62.1-binary
    - name: Install musl tools
      run: sudo apt-get install -y musl-tools
    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-musl
    - uses: actions/upload-artifact@v2
      with:
        name: linux
        path: target/x86_64-unknown-linux-musl/release/bwbackup

  macos-binary:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.62.1
        profile: minimal
        override: true
    - uses: Swatinem/rust-cache@v1
      with:
        key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}-1.62.1-binary
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: macos
        path: target/release/bwbackup

  windows-binary:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.62.1
        profile: minimal
        override: true
    - uses: Swatinem/rust-cache@v1
      with:
        key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}-1.62.1-binary
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: windows
        path: target/release/bwbackup.exe
